name: ECS Assignment Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test-workflow:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Verify workflow is running
        run: echo "Cloud computing assignment workflow is running successfully"
